### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [jiwoo181155/C202309#2]
### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week3/choiceIf
    - Error: expected ')' [line 7]
    - Error: expected ')' [line 20]
        -  쌍따옴표 위치가 잘못되어, 괄호를 제대로 인식하지 못하고있습니다. 쌍따옴표의 위치를 체크해주세요. 

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week2/police
    - 추출된 주석: s t d i o . h   컴 파 일

**Comment by jiwoo181155** [comment]
#2 오류를 전부 수정하였습니다
